import React, { useState, useEffect } from "react";
import { Card, Form, Button, Row, Col, Alert, Spinner } from "react-bootstrap";

const initialFormData = {
  firstName: "",
  lastName: "",
  email: "",
  course: "",
};

const AddStudentPage = ({
  editingStudent,
  onAddStudent,
  onUpdateStudent,
  onCancelEdit,
  onNavigateToHome,
}) => {
  const [formData, setFormData] = useState(initialFormData);
  const [formError, setFormError] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [successMessage, setSuccessMessage] = useState("");

  const isEditing = Boolean(editingStudent);

  useEffect(() => {
    if (editingStudent) {
      setFormData({
        firstName: editingStudent.firstName || "",
        lastName: editingStudent.lastName || "",
        email: editingStudent.email || "",
        course: editingStudent.course || "",
      });
      setFormError("");
      setSuccessMessage("");
    } else {
      setFormData(initialFormData);
    }
  }, [editingStudent]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
    if (formError) setFormError("");
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setFormError("");
    setSuccessMessage("");

    // Validations
    if (
      !formData.firstName.trim() ||
      !formData.lastName.trim() ||
      !formData.email.trim() ||
      !formData.course.trim()
    ) {
      setFormError("Please fill in all fields.");
      return;
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(formData.email.trim())) {
      setFormError("Please enter a valid email address.");
      return;
    }

    setSubmitting(true);
    try {
      if (isEditing) {
        const studentId = editingStudent._id || editingStudent.id;
        await onUpdateStudent(studentId, {
          firstName: formData.firstName.trim(),
          lastName: formData.lastName.trim(),
          email: formData.email.trim(),
          course: formData.course.trim(),
        });
        setSuccessMessage("Student details updated successfully!");
      } else {
        await onAddStudent({
          firstName: formData.firstName.trim(),
          lastName: formData.lastName.trim(),
          email: formData.email.trim(),
          course: formData.course.trim(),
        });
        setFormData(initialFormData);
        setSuccessMessage(
          "Student registered successfully! Backend assigned ID.",
        );
      }
    } catch (err) {
      setFormError(
        err.response?.data?.message || err.message || "Failed to submit form.",
      );
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="py-2" style={{ maxWidth: "640px", margin: "0 auto" }}>
      {/* Top breadcrumb/back link */}
      <div className="mb-3">
        <Button
          variant="link"
          className="text-decoration-none text-muted p-0 small fw-medium"
          onClick={onNavigateToHome}
        >
          ← Back to Students List
        </Button>
      </div>

      <Card className="border-0 shadow-sm rounded-3">
        <Card.Body className="p-4 p-md-5">
          <div className="mb-4">
            <h3 className="fw-bold tracking-tight text-dark mb-1">
              {isEditing ? "Edit Student Details" : "Add New Student"}
            </h3>
            <p className="text-muted small mb-0">
              {isEditing
                ? "Update the student information below and save changes."
                : "Enter student information. Student ID is automatically generated by the backend."}
            </p>
          </div>

          {/* Feedback Alerts */}
          {successMessage && (
            <Alert
              variant="success"
              className="border-0 shadow-sm mb-4 d-flex justify-content-between align-items-center"
            >
              <span className="small">{successMessage}</span>
              <Button
                variant="outline-success"
                size="sm"
                onClick={onNavigateToHome}
                className="ms-3 text-nowrap"
              >
                View Roster →
              </Button>
            </Alert>
          )}

          {formError && (
            <Alert variant="danger" className="border-0 shadow-sm mb-4 small">
              {formError}
            </Alert>
          )}

          <Form onSubmit={handleSubmit}>
            <Row className="g-3">
              <Col md={6}>
                <Form.Group controlId="firstName">
                  <Form.Label className="small fw-semibold text-secondary">
                    First Name <span className="text-danger">*</span>
                  </Form.Label>
                  <Form.Control
                    type="text"
                    name="firstName"
                    placeholder="e.g. John"
                    value={formData.firstName}
                    onChange={handleChange}
                    className="shadow-none py-2"
                    required
                  />
                </Form.Group>
              </Col>

              <Col md={6}>
                <Form.Group controlId="lastName">
                  <Form.Label className="small fw-semibold text-secondary">
                    Last Name <span className="text-danger">*</span>
                  </Form.Label>
                  <Form.Control
                    type="text"
                    name="lastName"
                    placeholder="e.g. Doe"
                    value={formData.lastName}
                    onChange={handleChange}
                    className="shadow-none py-2"
                    required
                  />
                </Form.Group>
              </Col>

              <Col xs={12}>
                <Form.Group controlId="email">
                  <Form.Label className="small fw-semibold text-secondary">
                    Email Address <span className="text-danger">*</span>
                  </Form.Label>
                  <Form.Control
                    type="email"
                    name="email"
                    placeholder="e.g. john.doe@university.edu"
                    value={formData.email}
                    onChange={handleChange}
                    className="shadow-none py-2"
                    required
                  />
                </Form.Group>
              </Col>

              <Col xs={12}>
                <Form.Group controlId="course">
                  <Form.Label className="small fw-semibold text-secondary">
                    Enrolled Course <span className="text-danger">*</span>
                  </Form.Label>
                  <Form.Control
                    type="text"
                    name="course"
                    placeholder="e.g. Computer Science, Full Stack Web Dev"
                    value={formData.course}
                    onChange={handleChange}
                    className="shadow-none py-2"
                    required
                  />
                </Form.Group>
              </Col>

              <Col xs={12} className="pt-2 d-flex gap-2">
                <Button
                  variant="dark"
                  type="submit"
                  disabled={submitting}
                  className="px-4 py-2 fw-medium shadow-sm flex-grow-1 flex-md-grow-0"
                >
                  {submitting ? (
                    <>
                      <Spinner animation="border" size="sm" className="me-2" />
                      {isEditing ? "Updating..." : "Adding..."}
                    </>
                  ) : isEditing ? (
                    "Save Changes"
                  ) : (
                    "Add Student"
                  )}
                </Button>

                {isEditing && (
                  <Button
                    variant="outline-secondary"
                    type="button"
                    onClick={onCancelEdit}
                    className="px-3 py-2"
                  >
                    Cancel
                  </Button>
                )}

                <Button
                  variant="light"
                  type="button"
                  onClick={onNavigateToHome}
                  className="border px-3 py-2 text-secondary"
                >
                  Close
                </Button>
              </Col>
            </Row>
          </Form>
        </Card.Body>
      </Card>
    </div>
  );
};

export default AddStudentPage;
